---
title: "my-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

```{r setup}
library(qcvid)

```

```{r}
# Load path------------------------------------------------------------------
procesados  <- file.path( "F:", "CERES2", "PREGVAL", "1-DATOS", 
                          "3-PROCESADOS")
```

This package contains `data.table::fread` helpers, which specify the type of columns (Integer, Date, etc.) for the following tables: **SIP**, **PCV**, **CEX**, **MBDS**, **AED**, **DIAGNOSES**, **MDR**, **PMR** and **EOS**.

# SIP

```{r}
# read sip file--------------------------------------------------------------
fread_sip(file.path(procesados, "sip.csv"), nrows = 10) |> gt()

```

# PCV

```{r}
# read pcv file--------------------------------------------------------------
 fread_pcv(file.path(procesados, "pcv.csv"), nrows = 10)    

```

# CEX

```{r}
# read cex file--------------------------------------------------------------
fread_cex(file.path(procesados, "cex.csv"), nrows = 10)    

```

# MBDS

```{r}
# read mbds file-------------------------------------------------------------
fread_mbds(file.path(procesados, "mbds.csv"), nrows = 10)    

```

# AED

```{r}
# read aed file--------------------------------------------------------------
fread_aed(file.path(procesados, "aed.csv"), nrows = 10)    

```

# DIAGNOSES

```{r}
# read diagnoses file--------------------------------------------------------
fread_diagnoses(file.path(procesados, "diagnoses.csv"), nrows = 10)    

```

# MDR

```{r}
# read mdr file--------------------------------------------------------------
fread_mdr(file.path(procesados, "mdr.csv"), nrows = 10)    

```

# PMR

```{r}
# read pmr file--------------------------------------------------------------
fread_pmr(file.path(procesados, "pmr.csv"), nrows = 10)    


```

# EOS

```{r}
# read eos file--------------------------------------------------------------
fread_eos(file.path(procesados, "eos.csv"), nrows = 10)    

```
